/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function(knex) {
  return knex.schema.createTable('users', (table) => {
    // UUID will be generated by application code
    table.string('id', 36).primary();
    table.string('email').notNullable().unique();
    table.string('phone').nullable().unique();
    table.string('password_hash').notNullable();
    table.string('first_name').notNullable();
    table.string('last_name').notNullable();
    table.string('id_number').nullable().unique(); // National ID
    table.string('role').defaultTo('citizen').checkIn(['admin', 'police', 'dci', 'ngo', 'investigator', 'citizen']);
    table.string('status').defaultTo('active').checkIn(['active', 'inactive', 'suspended']);
    table.string('organization').nullable(); // For police, NGO, etc.
    table.string('badge_number').nullable(); // For police officers
    table.string('profile_picture').nullable();
    table.text('permissions').nullable(); // JSON stored as text
    table.boolean('email_verified').defaultTo(false);
    table.boolean('phone_verified').defaultTo(false);
    table.string('verification_token').nullable();
    table.timestamp('last_login_at').nullable();
    table.string('reset_password_token').nullable();
    table.timestamp('reset_password_expires').nullable();
    table.text('notification_preferences').nullable(); // JSON stored as text
    table.decimal('default_latitude', 10, 8).nullable();
    table.decimal('default_longitude', 11, 8).nullable();
    table.integer('default_radius').defaultTo(10); // km
    table.timestamps(true, true);
    
    // Indexes
    table.index(['email']);
    table.index(['phone']);
    table.index(['role']);
    table.index(['status']);
    table.index(['organization']);
  });
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function(knex) {
  return knex.schema.dropTable('users');
};

